- name: Build DFRoot APK
        run: |
          ./gradlew :app:assembleDebug

      - name: Upload DFRoot APK
        uses: actions/upload-artifact@v7
        with:
          name: Gaming-Rahim-YT-APK
          path: app/build/outputs/apk/debug/*.apk
