- name: Validate signing config
        if: github.event_name != 'pull_request'
        run: |
          if [ "${{ secrets.KEYSTORE }}" = "" ]; then
            echo "::error::Signing secrets not configured. KEYSTORE secret is required for release builds."
            exit 1
          fi

      - name: Create signing.properties
        if: github.event_name != 'pull_request'
        run: |
          echo KEYSTORE_FILE=../keystore.jks > signing.properties
          echo KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> signing.properties
          echo KEY_ALIAS=${{ secrets.KEY_ALIAS }} >> signing.properties
          echo KEY_PASSWORD=${{ secrets.KEY_PASSWORD }} >> signing.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
